# This file was generated by GoReleaser. DO NOT EDIT.
cask "unusedfunc" do
  name "unusedfunc"
  desc "Find unused functions in Go code with high precision"
  homepage "https://github.com/715d/unusedfunc"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unusedfunc"

  on_macos do
    on_intel do
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-darwin-amd64.tar.gz"
      sha256 "b0069a3b2dd36cae9ac4f1eb7e403b5672b1c2ba18521158d3d99217d9fcaf09"
    end
    on_arm do
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-darwin-arm64.tar.gz"
      sha256 "f369265659b364a4a01e73f012e79f59d28346a4f17dc80088b00160238ec5ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-linux-amd64.tar.gz"
      sha256 "1b3ed0a37acc21e093dfec04a59f61e4fa7c3a3c0e3b42b6e19624a31e9599d3"
    end
    on_arm do
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-linux-arm64.tar.gz"
      sha256 "4b935f24c8ad63bd30536d4818d692f0743ee7b6a3951555e3dba0c799c1bef1"
    end
  end

  # No zap stanza required
end
