# This file was generated by GoReleaser. DO NOT EDIT.
cask "unusedfunc" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "1873af9affc325a09ebe2bc92424dea2b1d35cd738d5f7d4f995eea1495779ab"
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "d92981e03bfca967b9c115753a7ed2b27f7f9204fd90dfbb953f25f079b678ee"
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-darwin-amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0503bad805ba7373f545376c01262b2461dd938aebfa0ce8d8427d038744c338"
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "6a85a506586314ced3459c2d66ded5b8660399e6b143db624c2a1bcc6da0fe03"
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-linux-amd64.tar.gz"
    end
  end

  name "unusedfunc"
  desc "Find unused functions in Go code with high precision"
  homepage "https://github.com/715d/unusedfunc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unusedfunc"

  # No zap stanza required
end
