# This file was generated by GoReleaser. DO NOT EDIT.
cask "unusedfunc" do
  name "unusedfunc"
  desc "Find unused functions in Go code with high precision"
  homepage "https://github.com/715d/unusedfunc"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unusedfunc"

  on_macos do
    on_intel do
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-darwin-amd64.tar.gz"
      sha256 "fc7a71a0e3307f7fd7fe90f027c485d751403f117bae837c7ca09fb634960dbf"
    end
    on_arm do
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-darwin-arm64.tar.gz"
      sha256 "f9e3e749586753cbd815b93f6667341e9153e3c0371982afe126263a3e10d0db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-linux-amd64.tar.gz"
      sha256 "b0ff85e012750569bd016b8ef6f45517607de2c18f8e30f8350dfb240dc4919b"
    end
    on_arm do
      url "https://github.com/715d/unusedfunc/releases/download/v#{version}/unusedfunc-#{version}-linux-arm64.tar.gz"
      sha256 "da6b8446d23f66cabc7952715d3ce9bbe5f78e8125ffdda5fd7d83d45e96d50d"
    end
  end

  # No zap stanza required
end
